# Generated by Django 5.0.7 on 2026-07-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0001_initial"),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description du desaccord"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("en_investigation", "En investigation"),
                            ("resolue", "Resolue"),
                            ("rejetee", "Rejetee"),
                        ],
                        default="ouverte",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "decision",
                    models.TextField(
                        blank=True, default="", verbose_name="Decision rendue"
                    ),
                ),
                (
                    "favorable_au_client",
                    models.BooleanField(
                        blank=True,
                        help_text="Renseigne uniquement une fois la reclamation resolue",
                        null=True,
                        verbose_name="Favorable au client",
                    ),
                ),
                (
                    "resolu_avec_preuve",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Resolue avec preuve verifiable",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ouverte le"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolue le"
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reclamations",
                        to="commandes.commande",
                    ),
                ),
                (
                    "dossiers_concernes",
                    models.ManyToManyField(
                        help_text="Toutes les parties concernees par le desaccord",
                        related_name="reclamations",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "resolu_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="L'acteur humain ayant tranche, si resolution non automatique",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamations_resolues",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reclamation",
                "verbose_name_plural": "Reclamations",
                "ordering": ["-created_at"],
            },
        ),
    ]
