# Generated by Django 5.0.7 on 2026-07-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_engage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix engage (FCFA)",
                    ),
                ),
                (
                    "delai_annonce",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Delai annonce",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creee le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour le"),
                ),
                (
                    "dossier_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=150, verbose_name="Article")),
                ("service", models.CharField(max_length=100, verbose_name="Service")),
                (
                    "niveau_service",
                    models.CharField(
                        choices=[
                            ("complet", "Traitement complet"),
                            ("partiel", "Traitement partiel"),
                            ("specialise", "Intervention specialisee"),
                        ],
                        default="complet",
                        max_length=20,
                        verbose_name="Niveau de service",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantite"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("collecte", "Collectee"),
                            ("en_traitement", "En traitement"),
                            ("terminee", "Terminee"),
                            ("livree", "Livree"),
                            ("annulee", "Annulee"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut de la ligne",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="commandes.commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
    ]
