# Generated by Django 5.0.7 on 2026-07-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonnements", "0001_initial"),
        ("commandes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="abonnement",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigne uniquement si cette Commande a ete generee automatiquement/manuellement depuis un Abonnement - permet la detection anti-doublon par echeance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes_generees",
                to="abonnements.abonnement",
            ),
        ),
    ]
