# Generated by Django 5.0.7 on 2026-07-15 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(max_length=100, unique=True, verbose_name="Cle"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametre",
                "verbose_name_plural": "Parametres",
            },
        ),
        migrations.CreateModel(
            name="VersionParametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.CharField(max_length=255, verbose_name="Valeur")),
                (
                    "valide_a_partir_de",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Valide a partir de"
                    ),
                ),
                (
                    "valide_jusqu_a",
                    models.DateTimeField(
                        blank=True,
                        help_text="None = version courante, encore active",
                        null=True,
                        verbose_name="Valide jusqu'a",
                    ),
                ),
                (
                    "parametre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="configuration.parametre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de parametre",
                "verbose_name_plural": "Versions de parametre",
                "ordering": ["-valide_a_partir_de"],
            },
        ),
    ]
