services:
  - type: web
    name: fagni-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn fagniplatform.wsgi:application
    envVars:
      - key: SEED_SECRET_KEY
        value: fagni_seed_dev_2025
      - key: DJANGO_SETTINGS_MODULE
        value: fagniplatform.settings
