# Generated by Django 5.0.7 on 2026-07-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0001_initial"),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Code"),
                ),
                (
                    "pourcentage_reduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Pourcentage de reduction",
                    ),
                ),
                (
                    "usage_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="None = illimite",
                        null=True,
                        verbose_name="Usage maximum",
                    ),
                ),
                (
                    "usage_actuel",
                    models.PositiveIntegerField(default=0, verbose_name="Usage actuel"),
                ),
                (
                    "premiere_commande_uniquement",
                    models.BooleanField(
                        default=True, verbose_name="Premiere commande uniquement"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "valide_jusqu_a",
                    models.DateTimeField(
                        blank=True,
                        help_text="None = pas de date d'expiration",
                        null=True,
                        verbose_name="Valide jusqu'a",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_reduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant de la reduction (FCFA)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Applique le"),
                ),
                (
                    "commande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usage",
                        to="commandes.commande",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="pricing.coupon",
                    ),
                ),
                (
                    "dossier_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons_utilises",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de coupon",
                "verbose_name_plural": "Utilisations de coupon",
            },
        ),
    ]
