# Generated by Django 5.0.7 on 2026-07-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "toujours_humaine",
                    models.BooleanField(
                        default=False,
                        help_text="BOS chapitre 7.2 - ex: exclusion definitive d'un Dossier",
                        verbose_name="Toujours humaine (aucune exception)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regle de decision",
                "verbose_name_plural": "Regles de decision",
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau_applique",
                    models.CharField(
                        choices=[
                            ("automatique", "Automatique"),
                            ("assistee", "Assistee"),
                            ("humaine", "Humaine"),
                        ],
                        max_length=20,
                        verbose_name="Niveau applique",
                    ),
                ),
                ("objet_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "justification",
                    models.TextField(
                        blank=True, default="", verbose_name="Justification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Prise le"),
                ),
                (
                    "decideur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigne obligatoirement si niveau_applique='humaine'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_prises",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "objet_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "regle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="decisions.regladecision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision",
                "verbose_name_plural": "Decisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
