# Generated by Django 5.0.7 on 2026-07-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "service_associe",
                    models.CharField(
                        help_text="Correspond au champ 'service' des lignes de commande",
                        max_length=100,
                        verbose_name="Service associe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
            },
        ),
        migrations.CreateModel(
            name="EtapeWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("commande_creee", "Commande creee"),
                            ("collecte_commencee", "Collecte commencee"),
                            ("collecte_terminee", "Collecte terminee"),
                            ("inspection_realisee", "Inspection realisee"),
                            ("paiement_confirme", "Paiement confirme"),
                            ("mission_creee", "Mission creee"),
                            ("mission_acceptee", "Mission acceptee"),
                            ("service_termine", "Service termine"),
                            ("controle_qualite_realise", "Controle qualite realise"),
                            ("livraison_effectuee", "Livraison effectuee"),
                            ("avis_recu", "Avis recu"),
                            ("cloture", "Cloture"),
                            ("reclamation_ouverte", "Reclamation ouverte"),
                            ("reclamation_resolue", "Reclamation resolue"),
                            ("autre", "Autre (specifique a un workflow)"),
                        ],
                        max_length=40,
                        verbose_name="Type d'evenement",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(verbose_name="Ordre dans la sequence"),
                ),
                (
                    "obligatoire",
                    models.BooleanField(default=True, verbose_name="Etape obligatoire"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etape de workflow",
                "verbose_name_plural": "Etapes de workflow",
                "ordering": ["workflow", "ordre"],
            },
        ),
        migrations.AddConstraint(
            model_name="etapeworkflow",
            constraint=models.UniqueConstraint(
                fields=("workflow", "ordre"), name="unique_ordre_par_workflow"
            ),
        ),
    ]
