# Generated by Django 5.0.7 on 2026-07-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("commande_creee", "Commande creee"),
                            ("collecte_commencee", "Collecte commencee"),
                            ("collecte_terminee", "Collecte terminee"),
                            ("inspection_realisee", "Inspection realisee"),
                            ("paiement_confirme", "Paiement confirme"),
                            ("mission_creee", "Mission creee"),
                            ("mission_acceptee", "Mission acceptee"),
                            ("service_termine", "Service termine"),
                            ("controle_qualite_realise", "Controle qualite realise"),
                            ("livraison_effectuee", "Livraison effectuee"),
                            ("avis_recu", "Avis recu"),
                            ("cloture", "Cloture"),
                            ("autre", "Autre (specifique a un workflow)"),
                        ],
                        max_length=40,
                        verbose_name="Type d'evenement",
                    ),
                ),
                ("objet_source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "donnees",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Donnees complementaires"
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodate le"),
                ),
                (
                    "acteur_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_declenches",
                        to="dossiers.dossier",
                        verbose_name="Acteur a l'origine",
                    ),
                ),
                (
                    "dossiers_concernes",
                    models.ManyToManyField(
                        related_name="evenements",
                        to="dossiers.dossier",
                        verbose_name="Dossiers concernes",
                    ),
                ),
                (
                    "objet_source_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evenement",
                "verbose_name_plural": "Evenements",
                "ordering": ["-horodatage"],
            },
        ),
    ]
