# Generated by Django 5.0.7 on 2026-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("commande_creee", "Commande creee"),
                    ("collecte_commencee", "Collecte commencee"),
                    ("collecte_terminee", "Collecte terminee"),
                    ("inspection_realisee", "Inspection realisee"),
                    ("paiement_confirme", "Paiement confirme"),
                    ("mission_creee", "Mission creee"),
                    ("mission_acceptee", "Mission acceptee"),
                    ("service_termine", "Service termine"),
                    ("controle_qualite_realise", "Controle qualite realise"),
                    ("livraison_effectuee", "Livraison effectuee"),
                    ("avis_recu", "Avis recu"),
                    ("cloture", "Cloture"),
                    ("reclamation_ouverte", "Reclamation ouverte"),
                    ("reclamation_resolue", "Reclamation resolue"),
                    ("autre", "Autre (specifique a un workflow)"),
                ],
                max_length=40,
                verbose_name="Type d'evenement",
            ),
        ),
    ]
