# Generated by Django 5.2.16 on 2026-07-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acteur', models.CharField(choices=[('client', 'Client'), ('livreur', 'Livreur'), ('partenaire', 'Partenaire (atelier)'), ('artisan', 'Artisan specialise'), ('ops', 'Responsable OPS'), ('organisation', 'Organisation (entreprise, hotel, etc.)')], max_length=20, verbose_name="Type d'acteur")),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telephone')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu')], default='actif', max_length=20, verbose_name='Statut')),
                ('niveau_confiance', models.PositiveSmallIntegerField(default=50, verbose_name='Niveau de confiance (0-100)')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name='Ouvert le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='EntreeHistoriqueConfiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_niveau', models.PositiveSmallIntegerField(verbose_name='Ancien niveau')),
                ('nouveau_niveau', models.PositiveSmallIntegerField(verbose_name='Nouveau niveau')),
                ('raison', models.CharField(max_length=255, verbose_name='Raison du changement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistre le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_confiance', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': "Entree d'historique de confiance",
                'verbose_name_plural': 'Historique de confiance',
                'ordering': ['-created_at'],
            },
        ),
    ]
