# Generated by Django 5.2.16 on 2026-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
