# Generated by Django 5.2.16 on 2026-07-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
    ]
