# Generated by Django 5.0.7 on 2026-07-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "type_organisation",
                    models.CharField(
                        choices=[
                            ("entreprise_cliente", "Entreprise cliente"),
                            (
                                "pressing_multi_employes",
                                "Pressing a plusieurs employes",
                            ),
                            ("franchise", "Franchise"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("membre", "Membre"),
                            ("superviseur", "Superviseur"),
                            ("administrateur", "Administrateur"),
                        ],
                        default="membre",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compte",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel - un Compte peut ne dependre d'aucune organisation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
            },
        ),
    ]
