# Generated by Django 5.2.16 on 2026-07-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='mot_de_passe_hash',
            field=models.CharField(blank=True, default='', help_text='Jamais stocke en clair - toujours via definir_mot_de_passe()', max_length=255, verbose_name='Mot de passe (hache)'),
        ),
    ]
