# Generated by Django 5.0.7 on 2026-07-15 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjustementCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ajustement",
                    models.CharField(
                        choices=[
                            ("deficit", "Deficit (moins que declare)"),
                            ("excedent", "Excedent (plus que declare)"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "quantite_declaree",
                    models.PositiveIntegerField(verbose_name="Quantite declaree"),
                ),
                (
                    "quantite_reelle",
                    models.PositiveIntegerField(
                        verbose_name="Quantite reelle constatee"
                    ),
                ),
                (
                    "montant_ajustement",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant de l'ajustement (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("automatique_applique", "Applique automatiquement"),
                            (
                                "en_attente_complement",
                                "En attente de complement client",
                            ),
                            ("complement_paye", "Complement paye"),
                            ("complement_refuse", "Complement refuse par le client"),
                        ],
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Constate le"),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustements",
                        to="commandes.commande",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustements",
                        to="commandes.lignecommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajustement de commande",
                "verbose_name_plural": "Ajustements de commande",
                "ordering": ["-created_at"],
            },
        ),
    ]
