# Generated by Django 5.0.7 on 2026-07-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ajustements", "0001_initial"),
        ("commandes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ajustementcommande",
            name="ligne_commande",
            field=models.OneToOneField(
                help_text="Un seul ajustement possible par ligne - empeche structurellement le rejeu double",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ajustement",
                to="commandes.lignecommande",
            ),
        ),
    ]
