# Generated by Django 5.0.7 on 2026-07-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="Correspond au champ 'service' des lignes de commande",
                        max_length=100,
                        verbose_name="Service maitrise",
                    ),
                ),
                (
                    "niveau_confiance_service",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Distinct de la reputation generale du Dossier (BOS chapitre 4.5)",
                        verbose_name="Niveau de confiance sur ce service (0-100)",
                    ),
                ),
                (
                    "volume_disponible",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ce que le partenaire peut reellement absorber sur ce service maintenant",
                        verbose_name="Volume disponible",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Capacite active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Declaree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacites",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacite",
                "verbose_name_plural": "Capacites",
            },
        ),
        migrations.AddConstraint(
            model_name="capacite",
            constraint=models.UniqueConstraint(
                fields=("dossier", "service"), name="unique_capacite_dossier_service"
            ),
        ),
    ]
