# Generated by Django 5.2.16 on 2026-07-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description du besoin de devis')),
                ('montant_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant propose (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de proposition'), ('propose', 'Montant propose'), ('accepte', 'Accepte par le client'), ('refuse', 'Refuse par le client')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demande le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='commandes.commande')),
                ('ligne_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='commandes.lignecommande')),
                ('propose_par', models.ForeignKey(blank=True, help_text="L'acteur humain (artisan, partenaire) ayant propose le montant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_proposes', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
