# Generated by Django 5.0.7 on 2026-07-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0001_initial"),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mission",
                    models.CharField(
                        choices=[
                            ("collecte", "Collecte"),
                            ("livraison", "Livraison"),
                            ("transport_intermediaire", "Transport intermediaire"),
                        ],
                        max_length=30,
                        verbose_name="Type de mission",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("proposee", "Proposee"),
                            ("acceptee", "Acceptee"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminee"),
                            ("refusee", "Refusee"),
                        ],
                        default="proposee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creee le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour le"),
                ),
                (
                    "acteur_assigne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions_assignees",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="commandes.commande",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel - la mission peut concerner une ligne precise ou toute la commande",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="commandes.lignecommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-created_at"],
            },
        ),
    ]
