# Generated by Django 5.2.16 on 2026-07-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow selectionne par orchestrateur.selectionner_workflow() au moment de la creation - trace, jamais suppose.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='workflows.workflow'),
        ),
    ]
