# Generated by Django 5.2.16 on 2026-07-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_credit', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Montant du credit (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente_delai', 'En attente du delai de 48h'), ('credite', 'Credite'), ('refuse', 'Refuse')], default='en_attente_delai', max_length=20, verbose_name='Statut')),
                ('eligible_a_partir_de', models.DateTimeField(help_text='created_at + 48h, anti-fraude', verbose_name='Eligible a partir de')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistre le')),
                ('commande_declenchante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parrainages_declenches', to='commandes.commande')),
                ('filleul', models.OneToOneField(help_text="Un Dossier ne peut etre parraine qu'une seule fois", on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_recu', to='dossiers.dossier')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parrainages_effectues', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'ordering': ['-created_at'],
            },
        ),
    ]
