# Generated by Django 5.0.7 on 2026-07-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        ("evenements", "0001_initial"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_preuve",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("signature", "Signature"),
                            ("declaration_texte", "Declaration texte"),
                            ("position_gps", "Position GPS"),
                        ],
                        max_length=30,
                        verbose_name="Type de preuve",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="preuves/",
                        verbose_name="Fichier (photo, signature)",
                    ),
                ),
                (
                    "contenu_texte",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Contenu texte (declaration, notes)",
                    ),
                ),
                (
                    "metadonnees",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Metadonnees (GPS, contexte)",
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(auto_now_add=True, verbose_name="Capturee le"),
                ),
                (
                    "dossier_capturant",
                    models.ForeignKey(
                        help_text="L'acteur qui a physiquement capture cette preuve",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preuves_capturees",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        help_text="L'Evenement precis que cette Preuve vient etayer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preuves",
                        to="evenements.evenement",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preuves",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve",
                "verbose_name_plural": "Preuves",
                "ordering": ["-horodatage"],
            },
        ),
    ]
