# Generated by Django 5.2.16 on 2026-07-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        ('configuration', '0001_initial'),
        ('dossiers', '0003_alter_dossier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID de reference')),
                ('resume_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('service', models.CharField(default='pressing', max_length=50, verbose_name='Service')),
                ('strategy_version', models.CharField(default='pressing-v1', max_length=30, verbose_name='Version de strategie')),
                ('zone_code', models.CharField(help_text='Liste fermee de zones pilote (ex: RIVIERA_3) - portee par configuration.Parametre.', max_length=50, verbose_name='Zone')),
                ('taille_sac', models.CharField(choices=[('S', 'S'), ('M', 'M')], max_length=2, verbose_name='Taille sac')),
                ('pack', models.CharField(choices=[('essentiel', 'Essentiel'), ('confort', 'Confort')], max_length=20, verbose_name='Pack')),
                ('prix_calcule', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix calcule (FCFA)')),
                ('nb_partenaires_disponibles', models.PositiveIntegerField(default=0, verbose_name='Partenaires disponibles')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telephone')),
                ('nom', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resultat_affiche', 'Resultat affiche'), ('envoyee_whatsapp', 'Envoyee par WhatsApp'), ('reservee', 'Reservee'), ('commande_creee', 'Commande creee'), ('expiree', 'Expiree')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creee le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise a jour le')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_origine', to='abonnements.abonnement')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='dossiers.dossier')),
                ('simulation_precedente', models.ForeignKey(blank=True, help_text="Renseigne uniquement si cette Simulation nait du recalcul d'une simulation expiree.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_suivantes', to='simulateur.simulation')),
                ('version_parametre_prix', models.ForeignKey(help_text='Version tarifaire exacte utilisee pour ce calcul - jamais alteree retroactivement.', on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='configuration.versionparametre')),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvenementSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('arrivee', 'Arrivee'), ('etape_1', 'Etape 1 (taille sac)'), ('etape_2', 'Etape 2 (pack)'), ('resultat_affiche', 'Resultat affiche'), ('whatsapp_ouvert', 'WhatsApp ouvert'), ('reservation', 'Reservation'), ('commande_creee', 'Commande creee')], max_length=40, verbose_name='Type')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Donnees')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodate le')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulateur.simulation')),
            ],
            options={
                'verbose_name': 'Evenement de simulation',
                'verbose_name_plural': 'Evenements de simulation',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['sim_id'], name='simulateur__sim_id_a515f0_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['resume_token'], name='simulateur__resume__d2411b_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['created_at'], name='simulateur__created_5e189a_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['statut', 'created_at'], name='simulateur__statut_4779af_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementsimulation',
            index=models.Index(fields=['simulation', 'type_evenement'], name='simulateur__simulat_3c0b2c_idx'),
        ),
    ]
