# Generated by Django 5.0.7 on 2026-07-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        ("evenements", "0002_alter_evenement_type_evenement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("push", "Notification push"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "statut_envoi",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("envoyee", "Envoyee"),
                            ("echouee", "Echouee"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut d'envoi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "dossier_destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "evenement_declencheur",
                    models.ForeignKey(
                        help_text="Toute notification est declenchee par un Evenement precis (BOS chapitre 5)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="evenements.evenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("dossier_destinataire", "canal", "evenement_declencheur"),
                name="unique_notification_par_dossier_canal_evenement",
            ),
        ),
    ]
